[build]
  publish = "build"
  command = "npm run build"

[[edge_functions]]
  path = "/404"
  function = "handle404"

[[edge_functions]]
  path = "/503"
  function = "handle503"

[[edge_functions]]
  path = "/slow-load"
  function = "handleSlowLoad"

[context.production.environment]
  NODE_VERSION = "16"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200